import { Inter } from 'next/font/google'
import {TaskProvider} from '../context/TaskContext'
import { Navbar } from '@/components/Navbar'
import { Toaster } from 'react-hot-toast'
import "./globals.css"
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
     ///envuevlo el childer entre el contexto para proporcionarlo a toda la pagina
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
 
    <TaskProvider> 
    <header><Navbar/></header>
     {children}
    <Toaster/></TaskProvider>
      
        </body>
    </html>
  )
}
